### ISSUE TITLE
Add poll_read/poll_write and need_read/need_write

### ISSUE THREAD

**Issue by tailhook** [tokio-rs/tokio-io#33]
As described in tokio-rs/tokio-core#196 I need these methods to implement `sendfile` support. And yes, contrary to #6 it would be good to have them on trait object.

In the latter case, `tk-sendfile` don't have to depend on tokio-core **and** libraries that need sendfile support for their own streams (say a http library) can  implement `AsyncWrite + AsRawFd` instead of depending on `tk-sendfile` itself to a custom trait (because of coherence rules).

**Comment by carllerche** [comment]
IMO using `AsyncWrite + AsRawFd` doesn't feel like the right traits to provide OS specific functionality. Because *even* if a type implements `AsyncWrite + AsRawFd` doesn't mean it supports `sendfile` behavior. Maybe your crate could provide a trait itself? I know you said you didn't want to depend on `tokio-core`, but you could make it a cargo feature so that it is easy to opt in / out of it.

Asking all implementations of `AsyncWrite` to figure out how to impl `poll_write` / `need_write` feels onerous to me.

**Comment by alexcrichton** [comment]
Yeah I feel like the sendfile use case is best not handled with `AsyncWrite` and `AsRawFd`, but rather a custom trait implemented for specific types (if a trait is really necessary). 

@carllerche made a case for removing `poll_read`/write from the traits recently and it was convincing to me, so we'd want to add it back pretty carefully, if at all.

**Comment by carllerche** [comment]
I think the status quo has panned out well. I am going to close this for now, but if anyone disagrees, feel free to re-open.

**Comment by tailhook** [comment]
Well, the status quo is that we can't use sendfile. And with TLS implemented in recent kernel means we can use sendfile even for TLS connections. So this should be solved somehow.

**Comment by carllerche** [comment]
I'm not sure how the status quo means we can't use sendfile? I made a proposal and there was no response.
